const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const output=process.env.BROWSER_ARTIFACTS || '/tmp/myfitnesspal-browser';
fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'America/Los_Angeles'});
 const page=await context.newPage();
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:8765/?user=andrew.hunter');
 await page.locator('#dashboard').waitFor({state:'visible'});
 assert.equal(await page.locator('.session-card').count(),2);
 const today=await page.locator('#datePicker').inputValue();
 await page.screenshot({path:output+'/dashboard-mobile.png'});
 const center=await page.locator('#dateRoller').evaluate(el=>{const b=el.querySelector('[aria-pressed=true]'); return Math.abs(b.getBoundingClientRect().left+b.clientWidth/2-el.getBoundingClientRect().left-el.clientWidth/2)});
 assert.ok(center<5,`Selected date must be centered, error ${center}`);
 await page.locator('[data-session="1"]').click();
 assert.equal(await page.locator('.item').count(),7);
 await page.locator('.exercise summary').nth(2).click();
 assert.ok((await page.locator('.detail').nth(2).innerText()).includes('hold 5 sec'));
 await page.locator('.check').first().check();
 assert.equal(await page.locator('details[open]').count(),1,'Checking does not collapse details');
 await page.screenshot({path:output+'/workout-mobile.png'});
 await page.reload();
 await page.locator('#workout').waitFor({state:'visible'});
 assert.equal(await page.locator('.check').first().isChecked(),true);
 await page.locator('#backButton').click();
 assert.equal(await page.locator('#todayExercises').innerText(),'1 / 14');
 await page.locator('[data-session="2"]').click();
 assert.equal(await page.locator('.check').first().isChecked(),false);
 await page.locator('#backButton').click();
 await page.locator('#previousDate').click();
 assert.notEqual(await page.locator('#datePicker').inputValue(),today);
 await page.locator('[data-session="1"]').click();
 assert.equal(await page.locator('.check').first().isChecked(),false);
 await page.locator('#backButton').click();
 await page.locator('#todayButton').click();
 await page.locator('[data-session="1"]').click();
 for(const box of await page.locator('.check').all())await box.check();
 await page.locator('#backButton').click();
 assert.equal(await page.locator('#todaySessions').innerText(),'1 / 2');
 assert.equal(await page.locator('#weekSessions').innerText(),'1 / 14');
 assert.equal(await page.locator('.session-card.complete').count(),1);
 await page.locator('[data-session="1"]').click();
 for(const summary of await page.locator('summary').all()) await summary.click();
 await page.evaluate(async()=>{await Promise.all([...document.images].map(img=>{img.loading='eager';return img.decode()}))});
 assert.equal(await page.locator('.detail-image').count(),7);
 assert.equal(await page.evaluate(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0)),true);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.setViewportSize({width:1280,height:900});
 await page.locator('#backButton').click();
 await page.screenshot({path:output+'/dashboard-desktop.png'});
 await page.goto('http://localhost:8765/?user=unknown');
 assert.ok((await page.locator('#message').innerText()).includes('Choose a user'));
 // Corrupt storage never prevents loading.
 await page.evaluate(()=>localStorage.setItem('myfitnesspal:andrew.hunter:andrew-ankle-rehab:2026-10-03:session:1','broken'));
 await page.goto('http://localhost:8765/?user=andrew.hunter&date=2026-02-30&session=NaN');
 await page.locator('#dashboard').waitFor({state:'visible'});
 assert.equal(await page.locator('#datePicker').inputValue(),today);
 // Legacy prototype progress migrates once and doesn't recur on another date.
 const legacyContext=await browser.newContext({timezoneId:'America/Los_Angeles'});
 await legacyContext.addInitScript(()=>localStorage.setItem('myfitnesspal:andrew.hunter:andrew-ankle-rehab:session:2','["ankle-alphabet"]'));
 const legacy=await legacyContext.newPage();
 await legacy.goto('http://localhost:8765/?user=andrew.hunter');
 await legacy.locator('#dashboard').waitFor({state:'visible'});
 assert.equal(await legacy.locator('#todayExercises').innerText(),'1 / 14');
 await legacy.locator('#previousDate').click(); await legacy.locator('[data-session="2"]').click();
 assert.equal(await legacy.locator('.check').first().isChecked(),false);
 // Storage-disabled browser retains a usable checklist.
 const restricted=await browser.newContext();
 await restricted.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new Error('disabled')}}));
 const noStorage=await restricted.newPage();
 await noStorage.goto('http://localhost:8765/?user=andrew.hunter');
 await noStorage.locator('#dashboard').waitFor({state:'visible'});
 assert.ok((await noStorage.locator('#saveNotice').innerText()).includes('unavailable'));
 await noStorage.locator('[data-session="1"]').click();await noStorage.locator('.check').first().check();
 assert.equal(await noStorage.locator('#count').innerText(),'1 / 7 complete');
 assert.deepEqual(errors,[]);
 await browser.close();
 console.log('PASS: dashboard, centered date roller, exercise images/details, reload persistence, day/session isolation, metrics, legacy migration, malformed data, storage-disabled fallback and mobile/desktop layout');
})().catch(e=>{console.error(e);process.exit(1)});
